[package]
name = "csq"
version = "0.2.1"
edition = "2021"
description = "A Concurrent Set Queue implemented in Safe Rust."
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/hankjordan/csq"

[dependencies]
parking_lot = "0.12"
