[package]
name = "csq"
version = "0.1.0"
edition = "2021"
description = "A concurrent Set Queue."
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/hankjordan/csq"

[dependencies]
crossbeam-queue = "0.3"
dashmap = "5.4"
parking_lot = "0.12"
